name = "webgpu-worker-dev"
main = "build/worker/shim.mjs"
compatibility_date = "2023-01-15"
compatibility_flags = ["experimental", "nodejs_compat", "webgpu"]
usage_model = "unbound"
account_id = "3515b24d58ec616d11f4ce4290a02ac4"
logpush = true

[build]
command = "cargo install -q worker-build && set RUSTFLAGS=--cfg=web_sys_unstable_apis && worker-build --dev"

[[migrations]]
tag = "v1"
new_classes = ["Renderer"]

[durable_objects]
bindings = [
  { name = "RENDERER", class_name = "Renderer" }
]
